swagger: '2.0'
info:
  version: 0.0.1
  title: node-rest-starter-kit
host: '127.0.0.1:3333'
basePath: /api/v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /products:
    x-swagger-router-controller: products
    get:
      tags:
        - product
      operationId: getAll
      summary: get all products
      description: get all products
      responses:
        '200':
          description: return an array of product objects
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        '404':
          description: Product not found
        '500':
          description: error
          schema:
            $ref: '#/definitions/ErrorResponse'
    post:
      tags:
        - product
      operationId: create
      summary: create a new product
      parameters:
        - name: product
          description: new product
          in: body
          required: true
          schema:
            $ref: '#/definitions/Product'
      responses:
        '201':
          description: return the newly created product
          schema:
            $ref: '#/definitions/Product'
        '500':
          description: error
          schema:
            $ref: '#/definitions/ErrorResponse'
  '/products/{id}':
    x-swagger-router-controller: products
    get:
      tags:
        - product
      operationId: getSingle
      summary: get product by id
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: return the product
          schema:
            $ref: '#/definitions/Product'
        '404':
          description: product not found
        '500':
          description: error
          schema:
            $ref: '#/definitions/ErrorResponse'
    put:
      tags:
        - product
      operationId: update
      summary: update a product
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - name: product
          description: product to update
          in: body
          required: true
          schema:
            $ref: '#/definitions/Product'
      responses:
        '204':
          description: product has been updated successfully
        '404':
          description: product not found
        '500':
          description: error
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      tags:
        - product
      operationId: delete
      summary: delete a product
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        '204':
          description: product has been deleted successfully
        '404':
          description: product not found
        '500':
          description: error
          schema:
            $ref: '#/definitions/ErrorResponse'
  '/products/{id}/cancel':
    x-swagger-router-controller: products
    post:
      tags:
        - product
      operationId: cancel
      summary: cancel product by id
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        '204':
          description: product has been cancelled
        '404':
          description: product not found  
        '500':
          description: error
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  Product:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int32
      name:
        type: string
        description: product name
      state:
        type: integer
        description: product state
        enum:
          - 1
          - 2
      created_at:
        type: string
        format: date-time
        description: created at
      updated_at:
        type: string
        format: date-time
        description: updated at
  ErrorResponse:
    properties:
      error:
        type: string
